### ISSUE TITLE
Main difference between keymorph and brainmorph?

### ISSUE THREAD

**Issue by lzhzju** [alanqrwang/brainmorph#5]
I would like to ask what the main differences are between KeyMorph and BrainMorph? In my view, the network structures of the two seem to be identical.

**Comment by alanqrwang** [comment]
You are correct that the network structures of the two are identical, although BrainMorph has multiple variants of the network structure to choose from. 

To be clear, KeyMorph is a framework for training registration models, so it can be applied to any data that you want to register. In our MedIA paper, we used half-resolution brain data to verify that the framework works as proposed.

On the other hand, BrainMorph is specifically for brain MRIs and uses the KeyMorph framework. It is trained on full resolution with larger models, and thus it is intended for real world use cases where you want to register full resolution brain MRIs. If your use case fits these criteria, then BrainMorph provides an out-of-the-box solution. Otherwise, I would recommend using KeyMorph to train your own model on your own data.

Hope this helps.
